name: Node.js Package

on:
  release:
    types: [created]

defaults:
  run:
    working-directory: ./backend-es

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Setup PureScript dependencies
        run: npm i --global purescript@0.15.4 purs-tidy@latest spago@latest purescript-psa@latest
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
